font_family JetBrainsMono Nerd Font
font_size 13.0
background_opacity 0.90

# Kanagawa Dragon theme
foreground              #c5c9c5
background              #0d0d0d
selection_foreground    #0d0d0d
selection_background    #e2d9b3
cursor                  #e2d9b3
cursor_text_color       #0d0d0d

# Black
color0  #1a1a1a
color8  #2a2a2a

# Red
color1  #c4746e
color9  #c4746e

# Green
color2  #8a9a7b
color10 #8a9a7b

# Yellow
color3  #e2d9b3
color11 #e2d9b3

# Blue
color4  #8ba4b0
color12 #8ba4b0

# Magenta
color5  #a292a3
color13 #a292a3

# Cyan
color6  #8ea4a2
color14 #8ea4a2

# White
color7  #c5c9c5
color15 #e2d9b3
